def build_prompt(country_name, risk_score, metrics, headlines):
    ...

def generate_explanation(country_name, risk_score, metrics, headlines):
    ...

def fallback_explanation(country_name, risk_score):
    ...