def init_db():
    ...

def save_country_metrics(country_code, date, metrics):
    ...

def get_latest_country_metrics(country_code):
    ...

def get_country_series(country_code, metric, days=7):
    ...

def save_country_explanation(country_code, text):
    ...